server:
  port: 8899

base:
  uri: http://localhost:8763/user-service

api:
  version: api/v1

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: shcoco.generic@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true