apiVersion: v1
kind: ConfigMap
metadata:
  name: health-app-user-config
data:
  application.yml: |
    server:
      port: 9000

    spring:
      application:
        name: user-service
      output:
        ansi:
          enabled: ALWAYS
      datasource:
        url: jdbc:h2:mem:patientDB
        platform: org.hibernate.dialect.H2Dialect
      jpa:
        hibernate:
          ddl-auto: none
      main:
        allow-bean-definition-overriding: true
      mail:
        host: smtp.gmail.com
        port: 587
        username:
        password:
        properties:
          mail:
            smtp:
              auth: true

    keycloak:
      realm: master
      resource: health-app-be
      public-client: true
      ssl-required: external
      auth-server-url: http://keycloak-service:8080/

    app:
      keycloak:
        username: admin
        password: admin
        grant-type: password
        secret: 1378d4df-1d95-47bf-8864-11794d4a3f8f

    eureka:
      client:
        enabled: false

    base:
      uri: http://health-app-user-service:9000

    api:
      version: api/v1
