apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-user-service
  namespace: health-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-app-user-service
  template:
    metadata:
      labels:
        app: health-app-user-service
    spec:
      containers:
        - name: health-app-user-service
          image: health-app-user-service:1.0.0
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: health-app-user-config
---
apiVersion: v1
kind: Service
metadata:
  name: health-app-user-service
spec:
  selector:
    app: health-app-user-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
