spring:
  application:
    name: store
  datasource:
    url: jdbc:h2:mem:patientDB
    platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
#        starttls:
#          enable: true

keycloak:
  realm: master
  resource: health-app-be
  public-client: true
  ssl-required: external