spring:
  application:
    name: store
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:3306/healthapp
    username: ${DB_USER:root}
    password: ${DB_USER_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: healthapp
    url: jdbc:mysql://${DB_URL:localhost}:3306/healthapp
    user: ${DB_USER:root}
    password: ${DB_USER_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/projects
          jwt-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/projects/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true

keycloak:
  realm: master
  resource: health-app-be
  public-client: true
  ssl-required: external
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}/auth/

app:
  keycloak:
    username: ${KEYCLOAK_USER:admin}
    password: ${KEYCLOAK_USER_PASSWORD:admin}
    grant-type: password
    secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 8898