spring:
  application:
    name: store
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:patientDB
    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true

keycloak:
  realm: master
  resource: health-app-be
  public-client: true
  ssl-required: external
  auth-server-url: http://keycloak-service:8080/auth/

app:
  keycloak:
    username: admin
    password: admin
    grant-type: password
    secret: 1378d4df-1d95-47bf-8864-11794d4a3f8f
