spring:
  application:
    name: store
  datasource:
    url: jdbc:h2:mem:patientDB
    platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: master
  resource: health-app
  public-client: true
  ssl-required: external