apiVersion: v1
kind: ConfigMap
metadata:
  name: health-app-user-config
data:
  application.yml: |
    server:
      port: 8898
    spring:
      application:
        name: health-app-user-service
      datasource:
        url: jdbc:h2:mem:healthAppDB
        platform: org.hibernate.dialect.H2Dialect
        initialization-mode: always
      output:
        ansi:
          enabled: ALWAYS
      main:
        allow-bean-definition-overriding: true
      h2:
        console:
          enabled: true
      jpa:
        ddl-auto: none
      mail:
        host: smtp.gmail.com
        port: 587
        username: shcoco.generic@gmail.com
        password:
        properties:
          mail:
            smtp:
              auth: true
    #          starttls:
    #            enable: true

    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

    keycloak:
      realm: master
      auth-server-url: http://localhost:8080/auth/
      resource: health-app-be
      ssl-required: external
      cors: true

    app:
      keycloak:
        username: admin
        password: admin
        grant-type: password
        secret: 1378d4df-1d95-47bf-8864-11794d4a3f8f
