spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: core
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:3306/healthapp
    username: ${DB_USER:root}
    password: ${DB_USER_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: healthapp
    url: jdbc:mysql://${DB_URL:localhost}:3306/healthapp
    user: ${DB_USER:root}
    password: ${DB_USER_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/projects
          jwt-set-uri: http://localhost:8080/auth/realms/projects/protocol/openid-connect/certs


keycloak:
  realm: master
  resource: health-app-be
  ssl-required: external
  public-client: true
  auth-server-url: http://${KEYCLOAK_URL:localhost}:8080/auth/

app:
  keycloak:
    username: ${KEYCLOAK_USER:admin}
    password: ${KEYCLOAK_USER_PASSWORD:admin}
    grant-type: password
    secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 8896