spring:
  application:
    name: core
  datasource:
    url: jdbc:h2:mem:patientDB
    platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none

keycloak:
  realm: master
  resource: health-app
  ssl-required: external

app:
  keycloak:
    username: admin
    password: admin
    grant-type: password