spring:
  application:
    name: core
  datasource:
    url: jdbc:h2:mem:healthAppDB
    platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

keycloak:
  realm: master
  resource: health-app-be
  ssl-required: external
  public-client: true
  enable-cors: true

app:
  keycloak:
    username: admin
    password: admin
    grant-type: password