spring:
  application:
    name: health-app
  datasource:
    url: jdbc:h2:mem:patientDB
    platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth/
  resource: health-app
  public-client: true
  ssl-required: external

app:
  keycloak:
    username: admin
    password: admin
    grant-type: password